### PR TITLE
Fix plugin for Linux (installed via Jetbrains toolbox)

### LINKED ISSUE #2: Gemini cli not detecting IntelliJ on linux
I'm continuing [the conversation from the `gemini-cli` MR](https://github.com/google-gemini/gemini-cli/issues/9273#issuecomment-3666603286).

I can help debugging, but if you give me some pointers on how you debug it, it will be easier.

Thanks.

> Running gemini from the terminal didn't change the result, previous time when I started it from the button I already had a couple of terminals open.
> 
> I'm using IntelliJ.let me know if I can help debug and the steps I should take for that.
> 
> Thanks.
>

### PR DESCRIPTION
**Pull request by alcarraz**
- Analysis of the gemini-cli source code confirms a hardcoded check for `TERM_PROGRAM === 'vscode'` in `detect-ide.ts`.
- This check prevents the CLI from even attempting discovery in any non-VS Code terminal, regardless of spec compliance.
- Re-adding this variable is the only way to make the current version of the CLI work with the JetBrains IDE.

See https://github.com/google-gemini/gemini-cli/blob/86828bb561d5d2e15bb0f9e85f15231e44837342/packages/core/src/ide/detect-ide.ts#L90-L93

```typescript
  // Only VSCode-based integrations are currently supported.
  if (process.env['TERM_PROGRAM'] !== 'vscode') {
    return undefined;
  }
```

I created an issue in `gemini-cli` for that.

The other needed change was to add files for one upper level, since gemini cli is assuming a vscode IDE and it is looking for the grandparent process ID, instead of the parent that it seems would do. Perhaps we should file another issue for that. This should be handled better if they plan to support a variety of IDEs. For instance, they could traverse the process tree until they find a suitable file.

Closes #2

### CODE REVIEW

**Comment by SoLoHiC** [comment]
hi @alcarraz , brilliant work-arounds! i was trying to recover a previous commit to gemini-cli, providing ide detection for jetbrains IDEs...with your solution here, i don't think a PR to gemini-cli is necessary. yours can solve the connection failure from plugin side.

Just one more thing, have you tested it on your machine yet? i'm asking coz i noticed that gemini-cli requires a auth token (, written in port file or Terminal Env Var as fallback strategy) to connect MCP server created by plugin. i'm packing an update to align it though.

```
    this.connectionConfig = await this.getConnectionConfigFromFile();
    this.authToken =
      this.connectionConfig?.authToken ??
      process.env['GEMINI_CLI_IDE_AUTH_TOKEN'];
```

see [PR](https://github.com/google-gemini/gemini-cli/pull/14843/changes)

**Comment by alcarraz** [comment]
> hi @alcarraz , brilliant work-arounds! i was trying to recover a previous commit to gemini-cli, providing ide detection for jetbrains IDEs...with your solution here, i don't think a PR to gemini-cli is necessary. yours can solve the connection failure from plugin side.

Thanks, @SoLoHiC, I'm really grateful for your work, I couldn't get the momentum to undertake the endeavor of making this plugin, and it was something I really wanted. Now it is much closer.

Yeah, but I think they should fix that somehow, otherwise that variable doesn't have any meaning, perhaps just accept an unknown. I already created [the issue](https://github.com/google-gemini/gemini-cli/issues/15513)

> 
> Just one more thing, have you tested it on your machine yet? i'm asking coz i noticed that gemini-cli requires a auth token (, written in port file or Terminal Env Var as fallback strategy) to connect MCP server created by plugin. i'm packing an update to align it though.
> 
> ```
>     this.connectionConfig = await this.getConnectionConfigFromFile();
>     this.authToken =
>       this.connectionConfig?.authToken ??
>       process.env['GEMINI_CLI_IDE_AUTH_TOKEN'];
> ```
> 
> see [PR](https://github.com/google-gemini/gemini-cli/pull/14843/changes)

Actually, there were some more needed changes that got lost when I changed branches to push the code for making the PR. Not sure what happened. I'm working on getting those changes back, since I cannot pinpoint the specific changes and commits that really fixed the issue. That's why I marked this as draft.

But yes, at some point I had it working, I'll update this PR as soon as I find the needed changes.

File: src/main/kotlin/com/google/gemini/cli/TerminalEnvVarCustomizer.kt [hunk 1]
```diff
@@ -32,11 +32,14 @@ class TerminalEnvVarCustomizer : LocalTerminalCustomizer() {
...
         serverState.token?.let {
-            env["GEMINI_CLI_IDE_AUTH_TOKEN"] = it
+            env["GEMINI_CLI_IDE_SERVER_AUTH_TOKEN"] = it
         }
         serverState.workspacePath?.let {
             env["GEMINI_CLI_IDE_WORKSPACE_PATH"] = it
         }
+        // This is required to bypass a hardcoded check in `gemini-cli`
+        // which only allows IDE integration if TERM_PROGRAM is 'vscode'.
+        env["TERM_PROGRAM"] = "vscode"
```
Comment (mahdi-jfri) [inline src/main/kotlin/com/google/gemini/cli/TerminalEnvVarCustomizer.kt]: I managed to get the cli working without this in my env. Are you sure it's really necessary?

**Comment by SoLoHiC** [comment]
Hi @alcarraz , it looks good to me. will merge and publish in next version.
